import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Globe, Moon, Sun, ArrowLeft, ArrowRight } from 'lucide-react';
import { Logo } from '@components/common/Logo';
import { AnimatedBackground } from '@components/common/AnimatedBackground';
import { useThemeStore } from '@store/themeStore';
export const AuthLayout = ({ children, title, subtitle, showBackButton = false, }) => {
    const navigate = useNavigate();
    const { theme, toggleTheme, language, setLanguage, dir } = useThemeStore();
    const toggleLanguage = () => {
        setLanguage(language === 'ar' ? 'en' : 'ar');
    };
    return (_jsxs("div", { className: "relative min-h-screen w-full bg-brand-darkBg text-slate-100 flex flex-col justify-between overflow-x-hidden selection:bg-brand-purple/40", children: [_jsx(AnimatedBackground, { variant: "auth" }), _jsxs("header", { className: "relative z-20 w-full max-w-7xl mx-auto px-4 sm:px-8 py-6 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [showBackButton && (_jsx("button", { onClick: () => navigate(-1), className: "p-2.5 rounded-2xl bg-brand-card/80 border border-brand-cardBorder text-slate-300 hover:text-white hover:border-brand-purple transition-all duration-200", "aria-label": "Back", children: dir === 'rtl' ? _jsx(ArrowRight, { className: "w-5 h-5" }) : _jsx(ArrowLeft, { className: "w-5 h-5" }) })), _jsx(Logo, { size: "md" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("button", { onClick: toggleLanguage, className: "flex items-center gap-2 px-3.5 py-2 rounded-2xl bg-brand-card/80 border border-brand-cardBorder text-xs font-semibold text-slate-300 hover:text-white hover:border-brand-blue/60 transition-all duration-200", children: [_jsx(Globe, { className: "w-4 h-4 text-brand-blue" }), _jsx("span", { children: language === 'ar' ? 'English' : 'العربية' })] }), _jsx("button", { onClick: toggleTheme, className: "p-2.5 rounded-2xl bg-brand-card/80 border border-brand-cardBorder text-slate-300 hover:text-white hover:border-brand-purple transition-all duration-200", "aria-label": "Toggle theme", children: theme === 'dark' ? (_jsx(Sun, { className: "w-4 h-4 text-amber-400" })) : (_jsx(Moon, { className: "w-4 h-4 text-brand-blue" })) })] })] }), _jsx("main", { className: "relative z-10 flex-1 flex items-center justify-center px-4 py-8 sm:px-6 lg:px-8", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20, scale: 0.98 }, animate: { opacity: 1, y: 0, scale: 1 }, exit: { opacity: 0, y: -20, scale: 0.98 }, transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] }, className: "w-full max-w-md sm:max-w-lg", children: [(title || subtitle) && (_jsxs("div", { className: "text-center mb-8", children: [title && (_jsx("h1", { className: "text-2xl sm:text-3xl font-extrabold text-white tracking-tight mb-2", children: title })), subtitle && (_jsx("p", { className: "text-sm sm:text-base text-slate-400 font-medium", children: subtitle }))] })), children || _jsx(Outlet, {})] }) }), _jsxs("footer", { className: "relative z-20 w-full py-6 text-center text-xs text-slate-500 font-medium", children: ["\u00A9 ", new Date().getFullYear(), " Naghanish. ", language === 'ar' ? 'جميع الحقوق محفوظة.' : 'All rights reserved.'] })] }));
};
