import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Sparkles, X, ExternalLink } from 'lucide-react';
import { useThemeStore } from '@store/themeStore';
import { cn } from '@lib/utils';
export const AdSlot = ({ variant = 'banner', slotId = 'ad-slot-default', className = '', sponsorName = 'نغنِش VIP 👑', adText = 'احصل على اشتراك نغنِش الفائق لتلعب بدون إعلانات وتكسب ضعف النقاط!', adTextEn = 'Upgrade to Naghanish VIP to play ad-free and earn 2x XP!', targetUrl = '#', }) => {
    const { dir } = useThemeStore();
    const [dismissed, setDismissed] = useState(false);
    if (dismissed)
        return null;
    if (variant === 'in-feed') {
        return (_jsxs("div", { id: slotId, className: cn('relative p-5 rounded-3xl bg-gradient-to-r from-purple-950/40 via-brand-card to-indigo-950/40 border border-brand-purple/40 shadow-xl overflow-hidden my-4 group', className), children: [_jsxs("div", { className: "flex items-center justify-between gap-3 mb-2", children: [_jsxs("span", { className: "px-2 py-0.5 rounded-md bg-amber-500/20 text-amber-300 text-[10px] font-black uppercase tracking-wider border border-amber-500/30 flex items-center gap-1", children: [_jsx(Sparkles, { className: "w-3 h-3 text-amber-400" }), dir === 'rtl' ? 'إعلان مميز' : 'Sponsored'] }), _jsx("button", { onClick: () => setDismissed(true), className: "p-1 text-slate-500 hover:text-white rounded-lg transition-colors", title: dir === 'rtl' ? 'إغلاق الإعلان' : 'Dismiss Ad', children: _jsx(X, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-12 h-12 rounded-2xl bg-gradient-to-br from-brand-purple to-brand-orange flex items-center justify-center text-xl shrink-0 shadow-glow", children: "\uD83C\uDF81" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("h4", { className: "font-extrabold text-white text-sm flex items-center gap-2", children: [sponsorName, _jsx(ExternalLink, { className: "w-3 h-3 text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity" })] }), _jsx("p", { className: "text-xs text-slate-300 font-medium mt-0.5 line-clamp-2", children: dir === 'rtl' ? adText : adTextEn })] })] })] }));
    }
    if (variant === 'sidebar') {
        return (_jsxs("div", { id: slotId, className: cn('relative p-6 rounded-3xl bg-gradient-to-b from-brand-card via-brand-surface to-[#12182F] border border-brand-cardBorder text-center flex flex-col items-center gap-4 my-4 shadow-xl', className), children: [_jsxs("div", { className: "w-full flex items-center justify-between text-[10px] text-slate-400 font-bold uppercase tracking-wider", children: [_jsx("span", { children: dir === 'rtl' ? 'إعلان' : 'Ad' }), _jsx("button", { onClick: () => setDismissed(true), className: "text-slate-500 hover:text-white", children: _jsx(X, { className: "w-3.5 h-3.5" }) })] }), _jsx("div", { className: "w-16 h-16 rounded-3xl bg-gradient-to-br from-amber-400 to-orange-600 flex items-center justify-center text-3xl shadow-glow", children: "\u26A1" }), _jsxs("div", { children: [_jsx("h4", { className: "font-black text-white text-base", children: sponsorName }), _jsx("p", { className: "text-xs text-slate-300 font-medium mt-1", children: dir === 'rtl' ? adText : adTextEn })] }), _jsx("a", { href: targetUrl, className: "w-full py-2.5 rounded-2xl bg-gradient-to-r from-brand-purple to-brand-blue text-white font-bold text-xs shadow-glow hover:opacity-90 transition-opacity", children: dir === 'rtl' ? 'اكتشف المزيد' : 'Learn More' })] }));
    }
    if (variant === 'interstitial') {
        return (_jsx("div", { className: "fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4", children: _jsxs("div", { className: "relative w-full max-w-md p-6 rounded-3xl bg-gradient-to-b from-[#1A1A36] to-brand-card border-2 border-brand-purple/50 shadow-2xl flex flex-col items-center text-center gap-5", children: [_jsx("button", { onClick: () => setDismissed(true), className: "absolute top-4 right-4 rtl:right-auto rtl:left-4 p-2 rounded-xl bg-brand-darkBg text-slate-400 hover:text-white", children: _jsx(X, { className: "w-5 h-5" }) }), _jsx("span", { className: "px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-black uppercase tracking-wider border border-amber-500/30", children: dir === 'rtl' ? 'إعلان رعاية' : 'Sponsored Content' }), _jsx("div", { className: "w-20 h-20 rounded-3xl bg-gradient-to-br from-brand-purple via-indigo-600 to-brand-blue flex items-center justify-center text-4xl shadow-glow", children: "\uD83D\uDE80" }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-black text-white", children: sponsorName }), _jsx("p", { className: "text-sm text-slate-300 mt-2 font-medium", children: dir === 'rtl' ? adText : adTextEn })] }), _jsx("button", { onClick: () => setDismissed(true), className: "w-full py-3 rounded-2xl bg-gradient-to-r from-brand-purple to-brand-blue text-white font-black text-sm shadow-glow hover:scale-105 transition-transform", children: dir === 'rtl' ? 'متابعة إلى اللعبة 🎮' : 'Continue to Game 🎮' })] }) }));
    }
    // Default Banner Ad (Horizontal Top/Bottom)
    return (_jsxs("div", { id: slotId, className: cn('relative w-full p-4 rounded-2xl bg-brand-card/90 border border-brand-cardBorder flex items-center justify-between gap-4 shadow-lg my-3', className), children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "px-2 py-0.5 rounded bg-brand-purple/20 text-purple-300 text-[10px] font-black uppercase", children: dir === 'rtl' ? 'إعلان' : 'Ad' }), _jsx("p", { className: "text-xs font-bold text-slate-200", children: dir === 'rtl' ? adText : adTextEn })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("a", { href: targetUrl, className: "px-3 py-1 rounded-xl bg-brand-purple/30 hover:bg-brand-purple/50 text-white font-bold text-xs border border-brand-purple/40 transition-all shrink-0", children: dir === 'rtl' ? 'عرض' : 'View' }), _jsx("button", { onClick: () => setDismissed(true), className: "p-1 text-slate-500 hover:text-white transition-colors", children: _jsx(X, { className: "w-4 h-4" }) })] })] }));
};
