import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Gamepad2, Compass, ArrowRight, ArrowLeft } from 'lucide-react';
import { AuthLayout } from '@components/layout/AuthLayout';
import { Button } from '@components/common/Button';
import { useAuthStore } from '@store/authStore';
import { useThemeStore } from '@store/themeStore';
export const WelcomePage = () => {
    const navigate = useNavigate();
    const { user } = useAuthStore();
    const { dir } = useThemeStore();
    return (_jsx(AuthLayout, { children: _jsxs("div", { className: "p-8 rounded-3xl bg-brand-card/90 border border-brand-cardBorder shadow-2xl backdrop-blur-xl text-center flex flex-col items-center gap-6", children: [_jsxs(motion.div, { initial: { scale: 0.8, rotate: -10 }, animate: { scale: 1, rotate: 0 }, transition: { type: 'spring', stiffness: 300, damping: 20 }, className: "relative", children: [_jsx("div", { className: "w-24 h-24 sm:w-28 sm:h-28 rounded-3xl bg-gradient-to-br from-brand-purple via-purple-600 to-brand-blue flex items-center justify-center text-4xl shadow-glow-blue border-4 border-brand-card", children: "\uD83C\uDF89" }), _jsx("span", { className: "absolute -bottom-2 -right-2 rtl:-right-auto rtl:-left-2 px-3 py-1 rounded-full bg-brand-blue text-slate-950 text-xs font-black shadow-md", children: "LVL 12" })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl sm:text-3xl font-black text-white", children: dir === 'rtl' ? `أهلاً بك، ${user?.name || 'البطل'}! 👋` : `Welcome, ${user?.name || 'Player'}! 👋` }), _jsx("p", { className: "text-sm text-slate-300 font-medium mt-2 max-w-sm", children: dir === 'rtl'
                                ? 'مرحباً بك في عالم نغانيش! دعنا نخصص تجربتك لنقدم لك أفضل الألعاب والاختبارات الممتعة.'
                                : 'Welcome to Naghanish! Let’s customize your experience to serve you the best games & quizzes.' })] }), _jsxs("div", { className: "w-full grid grid-cols-2 gap-3 text-right rtl:text-right text-left", children: [_jsxs("div", { className: "p-4 rounded-2xl bg-brand-darkBg/60 border border-brand-cardBorder flex items-center gap-3", children: [_jsx("div", { className: "p-2.5 rounded-xl bg-purple-500/20 text-purple-300 shrink-0", children: _jsx(Gamepad2, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-white", children: dir === 'rtl' ? 'ألعاب ذكية' : 'Smart Games' }), _jsx("p", { className: "text-[10px] text-slate-400 font-medium", children: dir === 'rtl' ? 'توصيات AI' : 'AI Powered' })] })] }), _jsxs("div", { className: "p-4 rounded-2xl bg-brand-darkBg/60 border border-brand-cardBorder flex items-center gap-3", children: [_jsx("div", { className: "p-2.5 rounded-xl bg-cyan-500/20 text-cyan-300 shrink-0", children: _jsx(Compass, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-white", children: dir === 'rtl' ? 'غرف بارتي' : 'Party Rooms' }), _jsx("p", { className: "text-[10px] text-slate-400 font-medium", children: dir === 'rtl' ? 'لعب جماعي' : 'Multiplayer' })] })] })] }), _jsx(Button, { variant: "secondary", size: "lg", fullWidth: true, onClick: () => navigate('/choose-interests'), rightIcon: dir === 'rtl' ? _jsx(ArrowLeft, { className: "w-5 h-5" }) : _jsx(ArrowRight, { className: "w-5 h-5" }), className: "shadow-glow-blue mt-2", children: dir === 'rtl' ? 'اختر اهتماماتك 🎯' : 'Choose Your Interests 🎯' })] }) }));
};
