from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete
from datetime import datetime

from app.models.game import Game
from app.models.quiz import Quiz, QuizQuestion
from app.models.achievement import Achievement
from app.models.mission import DailyMission
from app.models.leaderboard import Tournament
from app.models.economy import StoreItem
from app.models.ai import AIQuestion

# Legacy IDs from the old 6-game catalog — removed on every seed sync.
LEGACY_GAME_IDS = ("g1", "g2", "g3", "g10", "g12", "g13")

# Official 22-game catalog (must stay in sync with frontend/src/data/games.data.ts).
INITIAL_GAMES = [
    # Arcade
    {
        "id": "g-hextris",
        "title_ar": "هيكستريس النيون 🔷",
        "title_en": "Cyber Hextris",
        "world": "arcade",
        "category": "Hexagon Puzzle",
        "category_ar": "أحاجي السداسي",
        "icon": "🔷",
        "color": "from-cyan-500 via-blue-600 to-purple-700",
        "plays": "48.2k",
        "stars": 4.9,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 400,
        "difficulty": "Medium",
        "desc_ar": "دور السداسي النيوني وجمّع 3 قوالب أو أكثر من نفس اللون لتفجير الخطوط والوصول لأعلى كومبو!",
        "desc_en": "Rotate the central hexagon and match falling color blocks to trigger mega line clears and combos!",
        "route": "/games/g-hextris",
    },
    {
        "id": "g-invaders",
        "title_ar": "صائد الفضاء النيوني 👾",
        "title_en": "Neon Space Invaders",
        "world": "arcade",
        "category": "Space Shooter",
        "category_ar": "إطلاق نار فضائي",
        "icon": "👾",
        "color": "from-violet-600 via-indigo-600 to-rose-600",
        "plays": "62.4k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 450,
        "difficulty": "Medium",
        "desc_ar": "دمّر أسراب الغزاة الفضائيين، التقط كبسولات الدروع والليزر المتعدد، واقضِ على الزعيم العملاق!",
        "desc_en": "Defend the galaxy against alien swarms, collect power-ups and shields, and defeat the cyber boss!",
        "route": "/games/g-invaders",
    },
    {
        "id": "g-snake",
        "title_ar": "ثعبان النيون المتطور 🐍",
        "title_en": "Neon Snake DX",
        "world": "arcade",
        "category": "Classic Arcade",
        "category_ar": "أركيد كلاسيكي",
        "icon": "🐍",
        "color": "from-emerald-500 via-teal-600 to-cyan-700",
        "plays": "81.9k",
        "stars": 5.0,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 350,
        "difficulty": "Medium",
        "desc_ar": "ثعبان النيون الكلاسيكي المطور ببوابات أبعاد، وتفاح ذهبي نادر يمنحك سرعة خارقة ومضاعفة نقاط!",
        "desc_en": "Upgraded neon snake with dimensional portal wrap walls, rare golden apples, and speed multipliers!",
        "route": "/games/g-snake",
    },
    {
        "id": "g-brick",
        "title_ar": "كسار الطوب النيوني 🧱",
        "title_en": "Arkanoid Brick Smasher",
        "world": "arcade",
        "category": "Brick Breaker",
        "category_ar": "تكسير القوالب",
        "icon": "🧱",
        "color": "from-amber-500 via-rose-600 to-red-600",
        "plays": "55.1k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 380,
        "difficulty": "Medium",
        "desc_ar": "سدد الكرة وحطم القوالب الصلبة والمتفجرة، التقط كبسولات تكبير المضرب والكرات المتعددة لإنهاء المراحل!",
        "desc_en": "Smash through armored and explosive bricks with laser paddles, multiballs, and dynamic bounce physics!",
        "route": "/games/g-brick",
    },
    # Reflex
    {
        "id": "g-rhythm",
        "title_ar": "نبض النيون الموسيقي 🎵",
        "title_en": "Cyber Rhythm Rush",
        "world": "reflex",
        "category": "Rhythm",
        "category_ar": "إيقاع ونغمات",
        "icon": "🎵",
        "color": "from-pink-500 via-rose-600 to-purple-700",
        "plays": "43.7k",
        "stars": 4.9,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 420,
        "difficulty": "Medium",
        "desc_ar": "اضغط النوتات الساقطة على المسارات الأربعة بتوقيت مثالي (Perfect) وحافظ على الكومبو حتى نهاية التحدي!",
        "desc_en": "Hit falling rhythm notes on 4 neon lanes with split-second timing to stack massive combo streaks!",
        "route": "/games/g-rhythm",
    },
    {
        "id": "g-dodge",
        "title_ar": "تفادي العقبات النفاثة ⚡",
        "title_en": "Cyber Dodge Runner",
        "world": "reflex",
        "category": "Speed Dodge",
        "category_ar": "تفادي سريع",
        "icon": "⚡",
        "color": "from-amber-400 via-orange-600 to-red-600",
        "plays": "51.3k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 390,
        "difficulty": "Hard",
        "desc_ar": "بدّل بين 3 مسارات لتفادي حواجز الليزر المتسارعة، اجمع دروع الحماية وكبسولات إبطاء الوقت Slow-Mo!",
        "desc_en": "Switch between 3 neon lanes at hypersonic speeds, dodge deadly lasers, and trigger bullet-time Slow-Mo!",
        "route": "/games/g-dodge",
    },
    {
        "id": "g-aim",
        "title_ar": "قناص الأهداف السريع 🎯",
        "title_en": "CQB Target Reflex",
        "world": "reflex",
        "category": "Aim & Precision",
        "category_ar": "تصويب ودقة",
        "icon": "🎯",
        "color": "from-emerald-500 via-cyan-600 to-blue-700",
        "plays": "67.0k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 360,
        "difficulty": "Medium",
        "desc_ar": "أصب 30 هدفاً خاطفاً بأسرع وقت وأعلى دقة. يقيس زمن استجابتك بالمللي ثانية ونسبة إصابتك بدقة متناهية!",
        "desc_en": "Eliminate 30 pop-up targets with clinical precision. Measures millisecond reaction time and accuracy!",
        "route": "/games/g-aim",
    },
    {
        "id": "g-reverse",
        "title_ar": "عكس الاتجاهات اللحظي 🔄",
        "title_en": "Reverse Brain Reflex",
        "world": "reflex",
        "category": "Mind Reflex",
        "category_ar": "رد فعل ذهني",
        "icon": "🔄",
        "color": "from-purple-600 via-violet-700 to-indigo-800",
        "plays": "39.8k",
        "stars": 4.7,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 380,
        "difficulty": "Hard",
        "desc_ar": "عندما يُطلب اليمين اضغط اليسار! تحديات عكس اتجاهات وألوان وأوامر لحظية مع مؤقت يتسارع بدون رحمة.",
        "desc_en": "Reverse your instincts: swipe opposite, pick contrary colors, and defy muscle memory under pressure.",
        "route": "/games/g-reverse",
    },
    # IQ Lab
    {
        "id": "g-2048",
        "title_ar": "نيون 2048 ديلوكس 🔢",
        "title_en": "2048 Cyber Deluxe",
        "world": "iqlab",
        "category": "Grid Puzzle",
        "category_ar": "أرقام واستراتيجية",
        "icon": "🔢",
        "color": "from-amber-500 via-orange-600 to-purple-700",
        "plays": "78.5k",
        "stars": 5.0,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 400,
        "difficulty": "Medium",
        "desc_ar": "ادمج المربعات النيونية حتى تصل لـ 2048 وما بعدها! مزودة بخاصية التراجع (Undo) وأوضاع شبكة 4×4 و 5×5.",
        "desc_en": "Slide and combine neon tiles to reach 2048 and beyond! Features tactical Undo moves and 5x5 grid mode.",
        "route": "/games/g-2048",
    },
    {
        "id": "g-sokoban",
        "title_ar": "دافع صناديق الطاقة 📦",
        "title_en": "Cyber Sokoban",
        "world": "iqlab",
        "category": "Warehouse Puzzle",
        "category_ar": "تخطيط ومسارات",
        "icon": "📦",
        "color": "from-cyan-600 via-blue-700 to-indigo-800",
        "plays": "32.1k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 450,
        "difficulty": "Hard",
        "desc_ar": "ادفع بطاريات الطاقة النيونية إلى محطات التفريغ الصحيحة بأقل عدد حركات ممكن في 15 لغزاً ذكياً!",
        "desc_en": "Push glowing power cells into energy docks with optimal paths across 15 handcrafted puzzle levels!",
        "route": "/games/g-sokoban",
    },
    {
        "id": "g-laser",
        "title_ar": "توجيه أشعة الليزر 🪞",
        "title_en": "Laser & Mirrors Matrix",
        "world": "iqlab",
        "category": "Optics Puzzle",
        "category_ar": "فيزياء وبصريات",
        "icon": "🪞",
        "color": "from-rose-500 via-red-600 to-amber-600",
        "plays": "29.4k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 460,
        "difficulty": "Hard",
        "desc_ar": "قم بتدوير المرايا بزوايا 45° لتوجيه شعاع الليزر المتوهج وتفادي الحواجز وإضاءة جميع المستشعرات!",
        "desc_en": "Rotate mirrors at 45° angles to redirect laser beams through obstacles and activate all targets!",
        "route": "/games/g-laser",
    },
    {
        "id": "g-mines",
        "title_ar": "كاسحة الألغام السيبرانية 💣",
        "title_en": "Minesweeper Cyber Hack",
        "world": "iqlab",
        "category": "Grid Deduction",
        "category_ar": "استنتاج وشفرات",
        "icon": "💣",
        "color": "from-teal-600 via-emerald-700 to-slate-900",
        "plays": "41.2k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 390,
        "difficulty": "Medium",
        "desc_ar": "حلل إشارات الدارات الإلكترونية واكتشف الفيروسات المخفية مع ميزة النقر المزدوج السريع (Chord Click)!",
        "desc_en": "Hack cybersecurity nodes and deduce hidden data-bombs using classic chord clicks and flags!",
        "route": "/games/g-mines",
    },
    # Shilla
    {
        "id": "g-draw",
        "title_ar": "ارسم وخمّن أونلاين 🎨",
        "title_en": "Draw & Guess Live",
        "world": "shilla",
        "category": "Party Drawing",
        "category_ar": "رسم وتخمين",
        "icon": "🎨",
        "color": "from-yellow-400 via-amber-500 to-orange-600",
        "plays": "94.6k",
        "stars": 5.0,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 420,
        "difficulty": "Easy",
        "desc_ar": "لوحة رسم بألوان متعددة وأحجام فرشاة متنوعة. ارسم الكلمة وخمّن رسومات الآخرين بأسرع وقت!",
        "desc_en": "Full canvas drawing tool with color palettes and brush sizes. Draw and guess words against time!",
        "route": "/games/g-draw",
    },
    {
        "id": "g-trivia",
        "title_ar": "مسابقة المعلومات الكبرى 🧠",
        "title_en": "Arabic Trivia Showdown",
        "world": "shilla",
        "category": "Live Trivia",
        "category_ar": "معلومات عامة",
        "icon": "🧠",
        "color": "from-blue-500 via-indigo-600 to-violet-700",
        "plays": "88.1k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 400,
        "difficulty": "Medium",
        "desc_ar": "بنك أسئلة عربي ضخم في الرياضة، التاريخ، العلوم، والجغرافيا مع وسائل مساعدة (حذف إجابتين، تمديد الوقت)!",
        "desc_en": "Massive Arabic trivia battle across sports, history, sciences, with 50:50 and time extension lifelines!",
        "route": "/games/g-trivia",
    },
    {
        "id": "g-wyr",
        "title_ar": "لو خيروك الأسطورية 🤔",
        "title_en": "Would You Rather Extreme",
        "world": "shilla",
        "category": "Party Dilemma",
        "category_ar": "اختيارات محرجة",
        "icon": "🤔",
        "color": "from-pink-500 via-rose-600 to-purple-600",
        "plays": "73.2k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 300,
        "difficulty": "Easy",
        "desc_ar": "خيارات مستحيلة ومواقف طريفة محرجة! صوّت واكتشف نسب اختيارات بقية لاعبي الشلة بشكل فوري.",
        "desc_en": "Hilarious and tough dilemmas! Choose your destiny and see live consensus percentages from players.",
        "route": "/games/g-wyr",
    },
    {
        "id": "g-impostor",
        "title_ar": "بروتوكول الجاسوس المخفي 🕵️",
        "title_en": "Cyber Impostor Protocol",
        "world": "shilla",
        "category": "Social Deduction",
        "category_ar": "كشف الجواسيس",
        "icon": "🕵️",
        "color": "from-emerald-600 via-teal-700 to-cyan-800",
        "plays": "56.8k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 480,
        "difficulty": "Hard",
        "desc_ar": "أنت في جلسة استجواب مع 5 روبوتات ذكية. الجميع يعرف كلمة السر إلا الجاسوس! اطرح الأسئلة واكشفه قبل فوات الأوان.",
        "desc_en": "Interrogate AI crew members where one is an undercover spy without the secret keyword. Find the imposter!",
        "route": "/games/g-impostor",
    },
    # Champions
    {
        "id": "g-stack",
        "title_ar": "برج التوازن الدقيق 🏗️",
        "title_en": "Tower Stack Deluxe",
        "world": "champions",
        "category": "Stacking",
        "category_ar": "بناء وتوازن",
        "icon": "🏗️",
        "color": "from-cyan-500 via-teal-600 to-emerald-600",
        "plays": "64.9k",
        "stars": 4.9,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 400,
        "difficulty": "Medium",
        "desc_ar": "ابنِ أطول ناطحة سحاب نيونية بدقة مليمترية. كل طابق متطابق تماماً يمنحك بونص ونغمة تصاعدية مذهلة!",
        "desc_en": "Stack moving neon blocks with surgical precision. Perfect alignment triggers bonus points and harmonic tones!",
        "route": "/games/g-stack",
    },
    {
        "id": "g-math",
        "title_ar": "مبارزة الحساب السريع ⚡",
        "title_en": "Speed Math Duel",
        "world": "champions",
        "category": "Mental Math",
        "category_ar": "حساب ذهني",
        "icon": "⚡",
        "color": "from-blue-600 via-indigo-600 to-purple-700",
        "plays": "49.1k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 420,
        "difficulty": "Hard",
        "desc_ar": "حل المسائل الحسابية في ثانيتين فقط! معادلات جمع، طرح، وضرب تتسارع وتتحدى سرعة بديهتك.",
        "desc_en": "Rapid-fire mental arithmetic duels with 2-second timers. Solve equations before the clock expires!",
        "route": "/games/g-math",
    },
    {
        "id": "g-pong",
        "title_ar": "بونغ النيون السيبراني 🏓",
        "title_en": "Cyber Pong 1v1",
        "world": "champions",
        "category": "Retro Sports",
        "category_ar": "رياضة سيبرانية",
        "icon": "🏓",
        "color": "from-violet-600 via-purple-700 to-pink-600",
        "plays": "58.3k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 380,
        "difficulty": "Medium",
        "desc_ar": "مباراة بونغ سريعة ضد ذكاء اصطناعي متكيف مع ضربات Smash القوية وذيول كرات نيونية متوهجة!",
        "desc_en": "Fast-paced cyber pong versus adaptive AI with power smash mechanics and glowing particle trails!",
        "route": "/games/g-pong",
    },
    # Chaos
    {
        "id": "g-micro",
        "title_ar": "ألعاب الخمس ثوانٍ الفوضوية ⏱️",
        "title_en": "Chaos Micro-Games",
        "world": "chaos",
        "category": "Wario Micro",
        "category_ar": "تحديات خاطفة",
        "icon": "⏱️",
        "color": "from-yellow-400 via-amber-500 to-rose-600",
        "plays": "76.4k",
        "stars": 5.0,
        "is_featured": True,
        "is_new": False,
        "xp_reward": 450,
        "difficulty": "Hard",
        "desc_ar": "12 تحدياً صغيراً بأسلوب WarioWare: اضغط، تجنب، وازن، التقط في 5 ثوانٍ فقط لكل لعبة برتم فوضوي متسارع!",
        "desc_en": "Rapid-fire 5-second micro-challenges inspired by WarioWare: tap, dodge, balance, and react before the fuse runs out!",
        "route": "/games/g-micro",
    },
    {
        "id": "g-roulette",
        "title_ar": "عجلة الحظ والأحكام الفوضوية 🌀",
        "title_en": "Glitch Roulette 2.0",
        "world": "chaos",
        "category": "Glitch Chance",
        "category_ar": "حظ وأحكام",
        "icon": "🌀",
        "color": "from-purple-600 via-fuchsia-600 to-rose-600",
        "plays": "52.0k",
        "stars": 4.8,
        "is_featured": False,
        "is_new": False,
        "xp_reward": 400,
        "difficulty": "Medium",
        "desc_ar": "عجلة فيزيائية تدور مع مؤثرات غليتش وفوضى. احصل على مضاعفات كبرى أو نفذ أحكاماً وتحديات غريبة!",
        "desc_en": "Physics-based glitch roulette wheel packed with wild multipliers, surprise dares, and chaos traps!",
        "route": "/games/g-roulette",
    },
    {
        "id": "g-gravity",
        "title_ar": "عداء الجاذبية المعكوسة 🌌",
        "title_en": "Gravity Invert Runner",
        "world": "chaos",
        "category": "Gravity Flip",
        "category_ar": "فيزياء مقلوبة",
        "icon": "🌌",
        "color": "from-emerald-500 via-teal-700 to-cyan-900",
        "plays": "47.6k",
        "stars": 4.9,
        "is_featured": False,
        "is_new": True,
        "xp_reward": 440,
        "difficulty": "Hard",
        "desc_ar": "اركض واعكس الجاذبية بين الأرض والسقف بلمسة واحدة لتفادي الحواجز المتوهجة في عالم فوضوي مشوش!",
        "desc_en": "Flip gravity between floor and ceiling instantly to navigate razor-sharp obstacles in a glitched world!",
        "route": "/games/g-gravity",
    },
]

INITIAL_QUIZZES = [
    {
        "id": "q1",
        "title_ar": "اختبار نمط القيادة واتخاذ القرار 👑",
        "title_en": "Executive Leadership Style 👑",
        "world": "iqlab",
        "category": "Personality",
        "category_ar": "شخصية",
        "questions_count": 3,
        "time_limit": "5m",
        "completions": "14.2k",
        "rating": 4.9,
        "badge": "Popular",
        "color": "from-amber-500 via-orange-600 to-yellow-600",
        "xp_reward": 250,
        "desc_ar": "اكتشف نمط قيادتك وقدرتك على توجيه الفريق وصناعة القرارات تحت الضغط.",
        "desc_en": "Discover your strategic leadership style and decision agility.",
        "route": "/quizzes/q1",
    },
    {
        "id": "q3",
        "title_ar": "مقياس الذكاء التحليلي والاستنتاج 🧠",
        "title_en": "Analytical Cognitive Scale 🧠",
        "world": "iqlab",
        "category": "IQ",
        "category_ar": "ذكاء",
        "questions_count": 3,
        "time_limit": "6m",
        "completions": "19.4k",
        "rating": 4.9,
        "badge": "Hot",
        "color": "from-violet-600 via-purple-700 to-pink-600",
        "xp_reward": 350,
        "desc_ar": "ألغاز هندسية ومنطقية عميقة لقياس مرونة عقلك وسرعة الاستنتاج الرياضي.",
        "desc_en": "Geometric and logical mind puzzles measuring pure deduction agility.",
        "route": "/quizzes/q3",
    },
]

INITIAL_QUIZ_QUESTIONS = [
    {
        "id": "qq_1",
        "quiz_id": "q1",
        "question_ar": "عندما يواجه فريقك موعد تسليم حرج ومفاجئ، ما هو تصرفك التلقائي؟",
        "question_en": "When facing a critical tight deadline, what is your default reaction?",
        "options": [
            {"id": "o1", "text": "أوزع المهام فوراً بناء على نقاط قوة كل عضو 📋", "trait": "الموجّه الاستراتيجي"},
            {"id": "o2", "text": "أتحمل الجزء الأكبر بنفسي لضمان الجودة والسرعة ⚡", "trait": "القائد التنفيذي"},
            {"id": "o3", "text": "أجتمع بالفريق لإيجاد حلول مبتكرة خارج الصندوق 💡", "trait": "القائد الملهم"},
        ],
    },
    {
        "id": "qq_2",
        "quiz_id": "q1",
        "question_ar": "كيف تتعامل مع اختلاف وجهات النظر داخل نقاشات العمل؟",
        "question_en": "How do you handle conflicting opinions in project discussions?",
        "options": [
            {"id": "o1", "text": "أستمع للجميع ثم أتخذ القرار النهائي الحاسم ⚖️", "trait": "الموجّه الاستراتيجي"},
            {"id": "o2", "text": "أعتمد على الأرقام والبيانات لحسم النقاش 📊", "trait": "القائد التحليلي"},
            {"id": "o3", "text": "أوفق بين الآراء للوصول لإجماع مشترك 🤝", "trait": "القائد التوافقي"},
        ],
    },
    {
        "id": "qq_3",
        "quiz_id": "q3",
        "question_ar": "إذا كان 3 عمال يبنون 3 كراسي في 3 دقائق، كم دقيقة يحتاج 100 عامل لبناء 100 كرسي؟",
        "question_en": "If 3 workers build 3 chairs in 3 minutes, how many minutes do 100 workers need to build 100 chairs?",
        "options": [
            {"id": "o1", "text": "3 دقائق ⏱️", "isCorrect": True},
            {"id": "o2", "text": "100 دقيقة ⏳", "isCorrect": False},
            {"id": "o3", "text": "33 دقيقة 🕒", "isCorrect": False},
        ],
    },
]

INITIAL_ACHIEVEMENTS = [
    {
        "id": "ach_first_game",
        "title_ar": "الخطوة الأولى 🚀",
        "title_en": "First Step 🚀",
        "desc_ar": "العب أول لعبة لك في أي عالم من عوالم نغنِش.",
        "desc_en": "Play your very first game in any Naghanish world.",
        "icon": "🚀",
        "category": "games",
        "tier": "bronze",
        "xp_reward": 250,
        "coins_reward": 50,
        "required_count": 1,
    },
    {
        "id": "ach_arcade_master",
        "title_ar": "سيد الأركيد 🕹️",
        "title_en": "Arcade Master 🕹️",
        "desc_ar": "أكمل 5 جلسات لعب في أي عالم.",
        "desc_en": "Complete 5 game sessions in any world.",
        "icon": "🕹️",
        "category": "arcade",
        "tier": "silver",
        "xp_reward": 500,
        "coins_reward": 100,
        "required_count": 5,
    },
    {
        "id": "ach_streak_hero",
        "title_ar": "بطل الاستمرارية 🔥",
        "title_en": "Streak Hero 🔥",
        "desc_ar": "أكمل 10 جلسات لعب على المنصة.",
        "desc_en": "Complete 10 game sessions on the platform.",
        "icon": "🔥",
        "category": "games",
        "tier": "gold",
        "xp_reward": 750,
        "coins_reward": 150,
        "required_count": 10,
    },
    {
        "id": "ach_high_score",
        "title_ar": "رقم قياسي 💯",
        "title_en": "High Score 💯",
        "desc_ar": "حقق سكور 1000 نقطة أو أكثر في أي لعبة.",
        "desc_en": "Score 1000 or more points in any single game.",
        "icon": "💯",
        "category": "games",
        "tier": "gold",
        "xp_reward": 800,
        "coins_reward": 200,
        "required_count": 1,
    },
    {
        "id": "ach_party_host",
        "title_ar": "روح الشلة 🎉",
        "title_en": "Party Animal 🎉",
        "desc_ar": "أنشئ غرفة والعب جولة كاملة مع أصدقائك في عالم الشلة.",
        "desc_en": "Host a room and play a full match with friends.",
        "icon": "🎉",
        "category": "party",
        "tier": "silver",
        "xp_reward": 500,
        "coins_reward": 100,
        "required_count": 1,
    },
    {
        "id": "ach_champion_throne",
        "title_ar": "عرش الأبطال 👑",
        "title_en": "Champion Throne 👑",
        "desc_ar": "ادخل قائمة أفضل 10 لاعبين في لوحة الصدارة العالمية.",
        "desc_en": "Reach the Top 10 on the Global Leaderboard.",
        "icon": "👑",
        "category": "champions",
        "tier": "diamond",
        "xp_reward": 2000,
        "coins_reward": 500,
        "required_count": 1,
    },
]

INITIAL_DAILY_MISSIONS = [
    {
        "id": "m_play_3_arcade",
        "title_ar": "بطل الأركيد اليومي 🕹️",
        "title_en": "Daily Arcade Hero 🕹️",
        "desc_ar": "العب 3 مباريات في كابينات عالم الأركيد.",
        "desc_en": "Play 3 matches in Arcade World cabinets.",
        "icon": "🕹️",
        "target_count": 3,
        "xp_reward": 350,
        "coins_reward": 75,
        "category": "daily",
        "target_action": "play_arcade_game",
    },
    {
        "id": "m_reflex_lightning",
        "title_ar": "صاعقة ردة الفعل ⚡",
        "title_en": "Reflex Lightning Strike ⚡",
        "desc_ar": "حقق 3 محاولات استجابة سريعة في حلبة السرعة.",
        "desc_en": "Achieve 3 fast reaction rounds in Speed Arena.",
        "icon": "⚡",
        "target_count": 3,
        "xp_reward": 400,
        "coins_reward": 80,
        "category": "daily",
        "target_action": "play_reflex_game",
    },
    {
        "id": "m_math_rapid",
        "title_ar": "تمرين العقل الصباحي 🧮",
        "title_en": "Morning Math Sprint 🧮",
        "desc_ar": "أكمل جولة حساب ذهني واحدة بنجاح.",
        "desc_en": "Complete 1 mental math calculation sprint.",
        "icon": "🧮",
        "target_count": 1,
        "xp_reward": 250,
        "coins_reward": 50,
        "category": "daily",
        "target_action": "play_any_game",
    },
    {
        "id": "m_shilla_invite",
        "title_ar": "اجتماع الشلة 🎉",
        "title_en": "Crew Gathering 🎉",
        "desc_ar": "ادخل غرفة لعب جماعي مع صديق.",
        "desc_en": "Join a party room with a friend.",
        "icon": "🎉",
        "target_count": 1,
        "xp_reward": 500,
        "coins_reward": 100,
        "category": "daily",
        "target_action": "join_party_room",
    },
]

INITIAL_TOURNAMENTS = [
    {
        "id": "t1",
        "title_ar": "كأس نغنِش الأسبوعي الكبرى 🏆",
        "title_en": "Weekly Grand Cup 🏆",
        "world": "champions",
        "prize_pool_xp": 25000,
        "prize_pool_coins": 5000,
        "participants_count": 256,
        "status": "active",
        "starts_at": datetime.utcnow(),
        "icon": "🏆",
        "color": "from-amber-400 via-yellow-500 to-amber-700",
    },
    {
        "id": "t2",
        "title_ar": "دوري سرعة البرق ⚡",
        "title_en": "Lightning Reflex League ⚡",
        "world": "reflex",
        "prize_pool_xp": 15000,
        "prize_pool_coins": 3000,
        "participants_count": 128,
        "status": "active",
        "starts_at": datetime.utcnow(),
        "icon": "⚡",
        "color": "from-red-500 via-rose-600 to-orange-500",
    },
    {
        "id": "t3",
        "title_ar": "بطولة عباقرة الحساب والمنطق 🧠",
        "title_en": "Mastermind IQ Open 🧠",
        "world": "iqlab",
        "prize_pool_xp": 18000,
        "prize_pool_coins": 3500,
        "participants_count": 96,
        "status": "upcoming",
        "starts_at": datetime.utcnow(),
        "icon": "🧠",
        "color": "from-purple-600 via-indigo-600 to-blue-600",
    },
]

INITIAL_STORE_ITEMS = [
    {
        "id": "item_avatar_robot",
        "title_ar": "أفاتار الروبوت الذهبي 🤖",
        "title_en": "Golden Bot Avatar 🤖",
        "desc_ar": "أفاتار حصري للاعبين المحترفين.",
        "desc_en": "Exclusive golden bot avatar for pro players.",
        "category": "avatar",
        "price_coins": 1000,
        "icon": "🤖",
        "rarity": "epic",
        "is_featured": True,
    },
    {
        "id": "item_title_legend",
        "title_ar": "لقب: أسطورة الصدارة 👑",
        "title_en": "Title: Leaderboard Legend 👑",
        "desc_ar": "لقب بريميوم يظهر بجوار اسمك في كل الغرف.",
        "desc_en": "Premium badge title appearing beside your nickname.",
        "category": "title",
        "price_coins": 2500,
        "icon": "👑",
        "rarity": "legendary",
        "is_featured": True,
    },
]

INITIAL_AI_QUESTIONS = [
    {
        "id": "aiq_1",
        "topic": "علوم وفضاء",
        "difficulty": "medium",
        "world": "iqlab",
        "question": "ما هو الكوكب الذي يمتلك أقوى مجال مغناطيسي في المجموعة الشمسية؟",
        "options": [
            {"id": "o1", "text": "كوكب المشتري 🪐", "isCorrect": True},
            {"id": "o2", "text": "كوكب زحل 🪐", "isCorrect": False},
            {"id": "o3", "text": "كوكب المريخ 🔴", "isCorrect": False},
            {"id": "o4", "text": "كوكب الأرض 🌍", "isCorrect": False},
        ],
        "explanation": "المشتري يمتلك مجالاً مغناطيسياً أقوى بنحو 20 ألف مرة من المجال المغناطيسي للأرض!",
        "xp_reward": 200,
    },
    {
        "id": "aiq_2",
        "topic": "تاريخ وحضارات",
        "difficulty": "medium",
        "world": "iqlab",
        "question": "ما هي أقدم مكتبة عامة معروفة في التاريخ لا تزال تعمل حتى اليوم؟",
        "options": [
            {"id": "o1", "text": "مكتبة القرويين بفاس 🏛️", "isCorrect": True},
            {"id": "o2", "text": "مكتبة الإسكندرية 📜", "isCorrect": False},
            {"id": "o3", "text": "مكتبة الفاتيكان 📚", "isCorrect": False},
            {"id": "o4", "text": "مكتبة الكونغرس 🏛️", "isCorrect": False},
        ],
        "explanation": "تأسست مكتبة جامعة القرويين في المغرب عام 859م على يد فاطمة الفهرية.",
        "xp_reward": 250,
    },
    {
        "id": "aiq_3",
        "topic": "ذكاء وألغاز",
        "difficulty": "easy",
        "world": "iqlab",
        "question": "شيء يزداد كلما أخذت منه، فما هو؟",
        "options": [
            {"id": "o1", "text": "الحفرة 🕳️", "isCorrect": True},
            {"id": "o2", "text": "الوقت ⏳", "isCorrect": False},
            {"id": "o3", "text": "العمر 🎂", "isCorrect": False},
            {"id": "o4", "text": "المال 💰", "isCorrect": False},
        ],
        "explanation": "الحفرة تتسع وتكبر كلما حفرت وأخذت منها تراباً!",
        "xp_reward": 150,
    },
]


async def _upsert_games_catalog(db: AsyncSession) -> None:
    """Replace legacy games and upsert the official 22-game catalog."""
    await db.execute(delete(Game).where(Game.id.in_(LEGACY_GAME_IDS)))

    for item in INITIAL_GAMES:
        existing = await db.get(Game, item["id"])
        if existing is None:
            db.add(Game(**item))
            continue
        for key, value in item.items():
            if key != "id":
                setattr(existing, key, value)


async def _upsert_by_id(db: AsyncSession, model, items: list[dict]) -> None:
    """Insert missing rows or refresh fields for existing primary keys."""
    for item in items:
        existing = await db.get(model, item["id"])
        if existing is None:
            db.add(model(**item))
            continue
        for key, value in item.items():
            if key != "id":
                setattr(existing, key, value)


async def seed_initial_data(db: AsyncSession):
    """Seed / sync catalog data so existing DBs pick up the official games."""
    await _upsert_games_catalog(db)

    # Quizzes & questions: insert only when empty (preserve custom content)
    res_q = await db.execute(select(Quiz).limit(1))
    if not res_q.scalars().first():
        for item in INITIAL_QUIZZES:
            db.add(Quiz(**item))

    res_qq = await db.execute(select(QuizQuestion).limit(1))
    if not res_qq.scalars().first():
        for item in INITIAL_QUIZ_QUESTIONS:
            db.add(QuizQuestion(**item))

    await _upsert_by_id(db, Achievement, INITIAL_ACHIEVEMENTS)
    await _upsert_by_id(db, DailyMission, INITIAL_DAILY_MISSIONS)

    res_t = await db.execute(select(Tournament).limit(1))
    if not res_t.scalars().first():
        for item in INITIAL_TOURNAMENTS:
            db.add(Tournament(**item))

    res_s = await db.execute(select(StoreItem).limit(1))
    if not res_s.scalars().first():
        for item in INITIAL_STORE_ITEMS:
            db.add(StoreItem(**item))

    res_ai = await db.execute(select(AIQuestion).limit(1))
    if not res_ai.scalars().first():
        for item in INITIAL_AI_QUESTIONS:
            db.add(AIQuestion(**item))

    await db.commit()

