import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { Sparkles, Gamepad2, Shield, Code } from 'lucide-react';
import { Logo } from '@components/common/Logo';
import { SectionTitle } from '@components/common/SectionTitle';
import { Button } from '@components/common/Button';
import { useThemeStore } from '@store/themeStore';
export const AboutPage = () => {
    const navigate = useNavigate();
    const { dir } = useThemeStore();
    return (_jsxs("div", { className: "w-full max-w-4xl mx-auto px-4 py-8 flex flex-col gap-8", children: [_jsx(SectionTitle, { title: dir === 'rtl' ? 'عن نغانيش ℹ️' : 'About Naghanish ℹ️', subtitle: dir === 'rtl' ? 'منصة الترفيه الذكية والتحديات الجماعية' : 'The modern entertainment & brain challenge platform', action: _jsx(Button, { variant: "outline", size: "sm", onClick: () => navigate(-1), children: dir === 'rtl' ? 'رجوع' : 'Back' }) }), _jsxs("div", { className: "p-8 rounded-3xl bg-gradient-to-br from-brand-card via-[#1A1A36] to-[#121226] border border-brand-cardBorder text-center flex flex-col items-center gap-6 shadow-2xl relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-64 h-64 bg-brand-purple/10 rounded-full blur-3xl pointer-events-none" }), _jsx(Logo, { size: "xl", animated: true }), _jsx("div", { className: "max-w-xl", children: _jsx("p", { className: "text-sm sm:text-base text-slate-300 font-medium leading-relaxed", children: dir === 'rtl'
                                ? 'نغانيش هي منصة ترفيه حديثة تجمع بين الألعاب الذهنية، اختبارات الشخصية، التحديات الجماعية المباشرة وتوصيات الذكاء الاصطناعي لتمنحك تجربة ممتعة ومحفزة يومياً!'
                                : 'Naghanish is a cutting-edge entertainment platform combining brain training games, personality tests, real-time party challenges, and AI recommendations to deliver a vibrant gaming experience everyday.' }) }), _jsxs("div", { className: "flex items-center justify-center gap-3 flex-wrap", children: [_jsxs("span", { className: "px-3.5 py-1.5 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/30 text-xs font-bold flex items-center gap-1.5", children: [_jsx(BrainIcon, {}), " Brain Games"] }), _jsxs("span", { className: "px-3.5 py-1.5 rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-400/30 text-xs font-bold flex items-center gap-1.5", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5" }), " AI Engine"] }), _jsxs("span", { className: "px-3.5 py-1.5 rounded-full bg-orange-500/20 text-orange-300 border border-orange-500/30 text-xs font-bold flex items-center gap-1.5", children: [_jsx(Gamepad2, { className: "w-3.5 h-3.5" }), " Party Multiplayer"] })] })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: [_jsxs("div", { className: "p-6 rounded-3xl bg-brand-card/80 border border-brand-cardBorder flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-center gap-3 text-brand-blue font-bold text-sm", children: [_jsx(Code, { className: "w-5 h-5" }), _jsx("span", { children: dir === 'rtl' ? 'التقنيات المستخدمة' : 'Tech Stack' })] }), _jsxs("ul", { className: "text-xs font-medium text-slate-300 flex flex-col gap-2", children: [_jsx("li", { children: "\u2022 React 19 & TypeScript" }), _jsx("li", { children: "\u2022 Vite & Tailwind CSS" }), _jsx("li", { children: "\u2022 Framer Motion & Zustand" }), _jsx("li", { children: "\u2022 TanStack Query & Lucide React" })] })] }), _jsxs("div", { className: "p-6 rounded-3xl bg-brand-card/80 border border-brand-cardBorder flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-center gap-3 text-brand-purple font-bold text-sm", children: [_jsx(Shield, { className: "w-5 h-5" }), _jsx("span", { children: dir === 'rtl' ? 'إصدار المنصة' : 'Platform Build' })] }), _jsxs("div", { className: "text-xs font-medium text-slate-300 flex flex-col gap-2", children: [_jsxs("p", { children: [_jsx("span", { className: "text-slate-500", children: "Version:" }), " 1.0.0 (Production Build)"] }), _jsxs("p", { children: [_jsx("span", { className: "text-slate-500", children: "Status:" }), " Connected & Fully Responsive"] }), _jsxs("p", { children: [_jsx("span", { className: "text-slate-500", children: "UI Identity:" }), " Official 3D Visual Identity"] })] })] })] })] }));
};
function BrainIcon() {
    return (_jsxs("svg", { className: "w-3.5 h-3.5", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" }), _jsx("path", { d: "M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" })] }));
}
